### ISSUE TITLE
Add Stable release to translate.wordpress.org

### ISSUE THREAD

**Issue by codiceovvio** [cedaro/simple-image-widget#17]
Hi and first of all **_Thank You**_ for this wonderful simple light and indispensable plugin _(it should be in core IMHO...;)_

I actually use it on different sites, and wanted to give a little help by translating it, but [in the project page](https://translate.wordpress.org/locale/it/default/wp-plugins/simple-image-widget) there is only the development version, and so the translations will not work correctly e.g. not pulled nor loaded (verified with plugin installed and language set to greek, which is shown as available in the WordPress repo plugin's page)

Could you please add also the Stable version there?
This way I think it should automatically reflect all current translations from Trunk and update live installs within a few hours

Thanks a lot, and thanks for all your efforts with the plugins you make!!

**Comment by bradyvercher** [comment]
Hi @codiceovvio, glad to hear you find the plugin useful and thanks for helping translate it!

I only use the WP.org repository for releasing new versions, which is why I use `trunk` for the stable version, although I do tag each release as well. I'm not well-versed on how language packs are supposed to work, but this is the first I've heard of the current workflow not working.

I just did some testing by switching a local install to Greek and it did pull down the translations for Simple Image Widget automatically. I then removed the translation files and checked for updates again and the translations for Simple Image Widget were pulled down again, so it seems to be working as expected.

Do you have Greek language files in `/wp-content/plugins/simple-image-widget/languages` or `/wp-content/languages/plugins` that might prevent translations from being pulled down?

**Comment by codiceovvio** [comment]
Hi @bradyvercher, in fact, you're totally right...I apologize for it, it was having a chat over slack with another translator who pointed me this thing, so before opening the issue I tested it but foolishly didn't think about checking for updates...!! Of course it works now that I did this!

I'm not versed into language packs behavior at all, and also in our translator community we had other related doubts, so this clarifies a little more and I will report back to translators in my community.
So, as for now Trunk is translated and soon will be readme and faqs too.
I apologize again, all the best and thanks, Marcello

**Comment by codiceovvio** [comment]
Hello @bradyvercher sorry to bother again...
talked with a GTE (general translation editor) for my language, and been told that the plugin it is not ok without a stable tag.
I noticed that the plugin gets translated, as well as FAQ, readme and changelog, so I can't tell you what exactly doesn't work because on my side it does work everything...
Anyway there is [a link he gave me](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#task-3) about this issue.
I never had a plugin to submit, as well as I don't use svn and I know very little about it, sorry but doing the ambassador is not my forte...
What can I do to help with this?

**Comment by bradyvercher** [comment]
@codiceovvio I finally got a chance to automate the release process so that the stable tag could be updated with each release. I just pushed version 4.4.1 to WordPress.org, so we'll see how that works. Thanks for following up on this!

**Comment by codiceovvio** [comment]
Hi @bradyvercher thanks for your kind reply,
and again for your plugin too! I will check in the afternoon, as for now it still displays only the development trunk. I think it is matter of few hours to receive the update in translate.wordpress.org
and then dev and stable should sync between each other.
Keep up with all your good work!!

**Comment by bradyvercher** [comment]
Hi @codiceovvio, after bumping the tested version in the readme today, it looks like [the stable version](https://translate.wordpress.org/projects/wp-plugins/simple-image-widget) was finally recognized, so I think this should be good to go now. Let me know if not.

Thanks again for helping translate Simple Image Widget!
